{% set name = "ydb" %}
{% set version = "3.21.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ydb-{{ version }}.tar.gz
  sha256: d1caf2bc706fc75e52dc990f13a4e964699fdb720e0142c05ffe5e2bc7e6c51e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - grpcio >=1.42.0
    - packaging
    - protobuf >=3.13.0,<6.0.0
    - aiohttp <4

test:
  imports:
    - ydb
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://github.com/ydb-platform/ydb-python-sdk
  summary: YDB Python SDK
  license: Apache-2.0
  license_file: LICENSE
  dev_url: http://github.com/ydb-platform/ydb-python-sdk
  doc_url: https://ydb-platform.github.io/ydb-python-sdk/

extra:
  recipe-maintainers:
    - xylar
